adminka/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path("month/", views.month_certif, name='month_certif'),
    path("end_certif/", views.end_certif, name='end_certif'),
    path('index/', views.home_page, name='index'),
    path('staff_page/', views.staff_page, name='staff'),
    path('staff_add/', views.upload_staff, name='add_staff'),
    path('staff_edit/<int:id>', views.edit_staff, name='edit_staff'),
    path('delete_staff/<int:id>', views.delete_staff, name='delete_staff'),
    path('rank_page/', views.rank_page, name='rank'),
    path('rank_upload/', views.upload_rank, name='add_rank'),
    path('edit_rank/<int:id>', views.edit_rank, name='edit_rank'),
    path('delete_rank/<int:id>', views.delete_rank, name='delete_rank'),
    path('unit_page/', views.unit_page, name='unit_page'),
    path('upload_unit/', views.upload_unit, name='upload_unit'),
    path('edit_unit/<int:id>', views.edit_unit, name='edit_unit'),
    path('delete_unit/<int:id>', views.delete_unit, name='delete_unit'),
    path('sertif_page/', views.certif_page, name='certif'),
    path('upload_certif/', views.upload_certif, name='add_certif'),
    path('edit_certif/<int:id>', views.edit_sertif, name='edit_certif'),
    path('delete_certif/<int:id>', views.delete_sertif, name='delete_certif'),
    path('region_page/', views.region_page, name='region'),
    path('region_upload/', views.upload_region, name='add_region'),
    path('edit_region/<int:id>', views.edit_region, name='edit_region'),
    path('delete_region/<int:id>', views.delete_region, name='delete_region'),

]

iiv/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('adminka/', include("adminka.urls")),
    path('staff/', include('staff.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

staff/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('gg/', views.test, name='t')
]

adminka/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractBaseUser


class AdminUser(models.Model):
    Choice = (
        ("1", "Toshkent shahar"),
        ("2", "Toshkent viloyati"),
        ("3", "Sirdaryo"),
        ("4", "Jizzax"),
        ("5", "Samarqand"),
        ("6", "Qashqadaryo"),
        ("7", "Surxondaryo"),
        ("8", "Buxoro"),
        ("9", "Navoiy"),
        ("10", "Xorazm"),
        ("11", "Qoraqalpoqiston"),
        ("12", "Andijon"),
        ("13", "Namangan"),
        ("14", "Farg'ona"),
    )
    user = models.OneToOneField(User, blank=True, null=True, related_name="admin_user", on_delete=models.DO_NOTHING)
    status = models.CharField(max_length=2, blank=True, null=True, choices=Choice)

    def __str__(self):
        return self.user.username

staff/models.py
from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title


class Region(models.Model):
    Choice = (
        ("1", "Toshkent shahar"),
        ("2", "Toshkent viloyati"),
        ("3", "Sirdaryo viloyati"),
        ("4", "Jizzax viloyati"),
        ("5", "Samarqand viloyati"),
        ("6", "Qashqadaryo viloyati"),
        ("7", "Surxondaryo viloyati"),
        ("8", "Buxoro viloyati"),
        ("9", "Navoiy viloyati"),
        ("10", "Xorazm viloyati"),
        ("11", "Qoraqalpoqiston Respublikasi"),
        ("12", "Andijon viloyati"),
        ("13", "Namangan viloyati"),
        ("14", "Farg'ona viloyati"),
    )
    region = models.CharField(max_length=225)
    # status = models.BooleanField(default=True)
    # parent = models.CharField(max_length=2,choices=Choice,null=True)
    # parent = models.ForeignKey('self', blank=True, null=True, related_name='childs', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Xudud'
        verbose_name_plural = 'Xududlar'

    def __str__(self):
        return self.region


class Rank(BaseModel):
    rank = models.CharField(max_length=455)

    class Meta:
        verbose_name = 'Lavozim'
        verbose_name_plural = 'Lavozimlar'

    def __str__(self):
        return self.rank


class Staff(BaseModel):

    STATUS = (
        ('not_iiv', "Hali IIV  uchun ko'rib chiqilmagan"),
        ('iiv', 'IIV'),
        ("delete_iiv", 'IIVdan chiqarilgan'),
    )

    first_name = models.CharField(max_length=125)
    last_name = models.CharField(max_length=125)
    father_name = models.CharField(max_length=125)
    birth_date = models.DateField()
    image = models.ImageField(upload_to='images',blank=True,null=True)
    status = models.CharField(max_length=40, choices=STATUS)
    rank = models.ForeignKey(Rank, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Xodim'
        verbose_name_plural = 'Xodimlar'

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)


class Unit(BaseModel):
    title = models.CharField(max_length=455)

    class Meta:
        verbose_name = "Tarkibiy Tuzilmasi"
        verbose_name_plural = 'Tarkibiy Tuzilmasi'

    def __str__(self):
        return self.title

#####

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

def validate_even(value):
    if value % 2 != 0:
        raise ValidationError(
            _('%(value)s is not an even number'),
            params={'value': value},
        )

    ####

class Certificate(BaseModel):
    staff = models.ForeignKey(Staff, related_name='staff', on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    given_region = models.ForeignKey(Region, on_delete=models.CASCADE)
    identification_num = models.CharField(max_length=20)
    serial_number = models.CharField(max_length=20)
    given_date = models.DateField()
    limit_date = models.DateField()

    class Meta:
        verbose_name = "Guvohnoma"
        verbose_name_plural = 'Guvohnomalar'

    def __str__(self):
        return '{} {}'.format(self.staff.first_name, self.staff.last_name)

adminka/forms.py
from django import forms
from staff.models import Unit, Region, Staff, Certificate, Rank


class RegionForm(forms.ModelForm):

    class Meta:
        model = Region
        fields = '__all__'


class StaffForm(forms.ModelForm):

    class Meta:
        model = Staff
        fields = '__all__'


class CertificateForm(forms.ModelForm):

    class Meta:
        model = Certificate
        fields = '__all__'


class RankForm(forms.ModelForm):

    class Meta:
        model = Rank
        fields = '__all__'


class UnitForm(forms.ModelForm):

    class Meta:
        model = Unit
        fields = '__all__'

adminka/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.db.models import Q
from django.core.paginator import Paginator
from .forms import UnitForm, RankForm, RegionForm, StaffForm, CertificateForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from staff.models import Region, Rank, Staff, Certificate, Unit
from django.contrib.auth.decorators import login_required
from datetime import datetime
import datetime


def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        print("user", user)
        if user is not None:
            login(request, user)
            return redirect('index')
        else:
            messages.info(request, 'username or password is incorrect')
    context = {}
    return render(request, 'login.html', context)


@login_required
def end_certif(request):
    if request.user.admin_user.status == '1':
        region = Region.objects.filter(Q(region='Toshkent'))
    elif request.user.admin_user.status == "2":
        region = Region.objects.filter(Q(region='Toshkent viloyati'))
    elif request.user.admin_user.status == "3":
        region = Region.objects.filter(Q(region='Sirdaryo'))
    elif request.user.admin_user.status == "4":
        region = Region.objects.filter(Q(region='Jizzax'))
    elif request.user.admin_user.status == "5":
        region = Region.objects.filter(Q(region='Samarqand'))
    elif request.user.admin_user.status == "6":
        region = Region.objects.filter(Q(region='Qashqadaryo'))
    elif request.user.admin_user.status == "7":
        region = Region.objects.filter(Q(region='Surxondaryo'))
    elif request.user.admin_user.status == "8":
        region = Region.objects.filter(Q(region='Buxoro'))
    elif request.user.admin_user.status == "9":
        region = Region.objects.filter(Q(region='Navoiy'))
    elif request.user.admin_user.status == "10":
        region = Region.objects.filter(Q(region='Xorazm'))
    elif request.user.admin_user.status == "11":
        region = Region.objects.filter(Q(region='Qoraqalpoqiston'))
    elif request.user.admin_user.status == '12':
        region = Region.objects.filter(Q(region='Andijon'))
    elif request.user.admin_user.status == "13":
        region = Region.objects.filter(Q(region='Namangan'))
    elif request.user.admin_user.status == "14":
        region = Region.objects.filter(Q(region="Farg'ona"))

    now = datetime.datetime.now()
    certifs = Certificate.objects.filter(given_region__in=region, limit_date__lte=now)

    return render(request, 'end_certif.html', {"certifs": certifs})


@login_required
def month_certif(request):
    if request.user.admin_user.status == '1':
        region = Region.objects.filter(Q(region='Toshkent'))
    elif request.user.admin_user.status == "2":
        region = Region.objects.filter(Q(region='Toshkent viloyati'))
    elif request.user.admin_user.status == "3":
        region = Region.objects.filter(Q(region='Sirdaryo'))
    elif request.user.admin_user.status == "4":
        region = Region.objects.filter(Q(region='Jizzax'))
    elif request.user.admin_user.status == "5":
        region = Region.objects.filter(Q(region='Samarqand'))
    elif request.user.admin_user.status == "6":
        region = Region.objects.filter(Q(region='Qashqadaryo'))
    elif request.user.admin_user.status == "7":
        region = Region.objects.filter(Q(region='Surxondaryo'))
    elif request.user.admin_user.status == "8":
        region = Region.objects.filter(Q(region='Buxoro'))
    elif request.user.admin_user.status == "9":
        region = Region.objects.filter(Q(region='Navoiy'))
    elif request.user.admin_user.status == "10":
        region = Region.objects.filter(Q(region='Xorazm'))
    elif request.user.admin_user.status == "11":
        region = Region.objects.filter(Q(region='Qoraqalpoqiston'))
    elif request.user.admin_user.status == '12':
        region = Region.objects.filter(Q(region='Andijon'))
    elif request.user.admin_user.status == "13":
        region = Region.objects.filter(Q(region='Namangan'))
    elif request.user.admin_user.status == "14":
        region = Region.objects.filter(Q(region="Farg'ona"))

    now = datetime.datetime.now()
    one_month = now + datetime.timedelta(30)
    certifs = Certificate.objects.filter(given_region__in=region, limit_date__gte=now, limit_date__lte=one_month)
    # output = ','.join(i.given_date for i in certifs)
    # return HttpResponse(output)
    return render(request, 'month_certif.html', {"certifs": certifs})


@login_required
def home_page(request):
    return render(request, 'home.html')


@login_required
def staff_page(request):

    staff_count = Staff.objects.count()
    search = request.GET.get('search')
    if search:
        search_staff = Staff.objects.filter(
            Q(first_name__icontains=search) | Q(last_name__icontains=search)
        )
        staffs = search_staff
    else:
        staffs = Staff.objects.all()
    if len(staffs) >= 7:
        paginator = Paginator(staffs, 6)
        page = request.GET.get('page')
        staffs = paginator.get_page(page)
    return render(request, 'staff.html', {'staffs': staffs, 'staff_count': staff_count})


@login_required
def upload_staff(request):
    ranks = Rank.objects.all()
    if request.method == 'POST':
        upload = StaffForm(request.POST, request.FILES)
        if upload.is_valid():
            if "add_text" in request.POST:
                upload.save()
                return redirect('add_staff')
            else:
                upload.save()
                return redirect("staff")
        else:
            upload.save()
            return redirect("staff")
        # else:
        #     print("dsfsdf", upload.errors)
        #     return HttpResponse("""your form is wrong, reload on <a href = "{{ url 'index' }}">reload</a>""")
    else:
        return render(request, 'staff_add.html', {'ranks': ranks})


@login_required
def edit_staff(request, id):
    ranks = Rank.objects.all()
    id = str(id)
    try:
        staff = Staff.objects.get(id=id)
    except Staff.DoesNotExist:
        return redirect('staff')
    staff_form = StaffForm(request.POST or None, instance=staff,files=request.FILES)
    if staff_form.is_valid():
        staff_form.save()
        return redirect('staff')
    else:
        print('afdf', staff_form.errors)
    return render(request, 'staff_edit.html', {'staff': staff, 'ranks': ranks})


@login_required
def delete_staff(request, id):
    id = int(id)
    try:
        product = Staff.objects.get(id=id)
    except Staff.DoesNotExist:
        return redirect('staff')
    product.delete()
    return redirect('staff')


@login_required
def rank_page(request):
    rank_count = Rank.objects.count()
    search = request.GET.get('search')
    if search:
        search_rank = Rank.objects.filter(
            Q(rank__icontains=search)
        )
        ranks = search_rank
    else:
        ranks = Rank.objects.all()
    if len(ranks) >= 10:
        paginator = Paginator(ranks, 9)
        page = request.GET.get('page')
        ranks = paginator.get_page(page)
    return render(request, 'rank.html', {'ranks': ranks, 'rank_count': rank_count})


@login_required
def upload_rank(request):
    upload = RankForm()
    ranks = Rank.objects.all()
    if request.method == 'POST':
        upload = RankForm(request.POST, request.FILES)
        print("dsdsds", request.POST, request.FILES)
        if upload.is_valid():
            print(True)
            if "add_text" in request.POST:
                upload.save()
                return redirect('add_rank')
            else:
                upload.save()
                return redirect("rank")
        else:
            print("errrrorrr", upload.errors)
            return HttpResponse('xatolik')
        # else:
        #     print(upload.errors)
        #     return HttpResponse("""your form is wrong, reload on <a href = "{% url 'product_page' %}">reload</a>""")
    else:
        return render(request, 'rank_add.html')



@login_required
def edit_rank(request, id):
    id = str(id)
    try:
        rank = Rank.objects.get(id=id)
    except Rank.DoesNotExist:
        return redirect('rank')
    product_form = RankForm(request.POST or None, instance=rank)
    if product_form.is_valid():
        product_form.save()
        return redirect('rank')
    return render(request, 'rank_edit.html', {'rank': rank})


@login_required
def delete_rank(request, id):
    id = int(id)
    try:
        product = Rank.objects.get(id=id)
    except Rank.DoesNotExist:
        return redirect('rank')
    product.delete()
    return redirect('rank')


@login_required
def region_page(request):
    search = request.GET.get('search')
    if search:
        search_categ = Region.objects.filter(
            Q(region__icontains=search)
        )
        regions = search_categ
    else:
        regions = Region.objects.all()
    if len(regions) >= 10:
        paginator = Paginator(regions, 9)
        page = request.GET.get('page')
        regions = paginator.get_page(page)
    return render(request, 'region.html', {'regions': regions})


@login_required
def upload_region(request):
    regions = Region.objects.all()
    if request.method == 'POST':
        upload = RegionForm(request.POST, request.FILES)
        if upload.is_valid():
            if "add_text" in request.POST:
                upload.save()
                return redirect('add_region')
            else:
                upload.save()
                return redirect("region")
        # else:
        #     print(upload.errors)
        #     return HttpResponse("""your form is wrong, reload on <a href = "{{ url : 'index'}}">reload</a>""")
    else:
        return render(request, 'region_add.html', {'regions': regions})


@login_required

staff/views.py
from django.shortcuts import render
from django.http import HttpResponse


def test(request):
    return HttpResponse("html")

adminka/templates/certif_add.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
    <!--end::Card-->
    <!--begin::Card-->
    <div class="card card-custom gutter-b example example-compact">
        <div class="card-header">
            <h3 class="card-title"></h3>
            <div class="card-toolbar">
                <div class="example-tools justify-content-center">
                    <span class="example-toggle" data-toggle="tooltip" title="View code"></span>
                    <span class="example-copy" data-toggle="tooltip" title="Copy code"></span>
                </div>
            </div>
        </div>
        <!--begin::Form-->
       <form method="POST" action="" enctype="multipart/form-data">
                         {% csrf_token %}
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="alert alert-custom alert-default" role="alert">
                        <div class="alert-icon">
                            <span class="svg-icon svg-icon-primary svg-icon-xl">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Tools/Compass.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <path d="M7.07744993,12.3040451 C7.72444571,13.0716094 8.54044565,13.6920474 9.46808594,14.1079953 L5,23 L4.5,18 L7.07744993,12.3040451 Z M14.5865511,14.2597864 C15.5319561,13.9019016 16.375416,13.3366121 17.0614026,12.6194459 L19.5,18 L19,23 L14.5865511,14.2597864 Z M12,3.55271368e-14 C12.8284271,3.53749572e-14 13.5,0.671572875 13.5,1.5 L13.5,4 L10.5,4 L10.5,1.5 C10.5,0.671572875 11.1715729,3.56793164e-14 12,3.55271368e-14 Z" fill="#000000" opacity="0.3" />
                                        <path d="M12,10 C13.1045695,10 14,9.1045695 14,8 C14,6.8954305 13.1045695,6 12,6 C10.8954305,6 10,6.8954305 10,8 C10,9.1045695 10.8954305,10 12,10 Z M12,13 C9.23857625,13 7,10.7614237 7,8 C7,5.23857625 9.23857625,3 12,3 C14.7614237,3 17,5.23857625 17,8 C17,10.7614237 14.7614237,13 12,13 Z" fill="#000000" fill-rule="nonzero" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span>
                        </div>

                    </div>
                </div>
                <div class="form-group">
            <label >Xodim</label>
            <select class="form-control" name="staff" required id ="id_staff">
                <option value="">-----------</option>
                {% for staff in staffs %}
                  <option value="{{staff.id}}">{{ staff.first_name }} {{ staff.last_name }}</option>
                {% endfor %}

            </select>
        </div>
        <div class="form-group">
    <label >Xudud</label>
    <select class="form-control" name="given_region" required="id_given_region">
        <option value="">-----------</option>
        {% for region in admin_region %}
          <option value="{{region.id}}">{{ region.region }}</option>
        {% endfor %}

    </select>
</div>
	<div class="form-group">
        <label>Berilgan sana</label>

            <input class="form-control" type="date" value="" name="given_date" id="example-date-input" required="id_given_date" />

    </div>

<div class="form-group">
        <label>Bekor qilingan sana</label>

            <input class="form-control" type="date" value="" name="limit_date" required = "id_limit_date" />

    </div>
<div class="form-group">
                    <label>Identification</label>
                    <input  class="form-control" type="text" name="identification_num" required="id_identification_num">
                </div>
<div class="form-group">
                    <label>Seriya raqami</label>
                    <input  class="form-control" type="text" name="serial_number" required="id_serial_number">
                </div>
{#<div class="form-group">#}
{#        <label>Status</label>#}
{#        <div class="checkbox-list">#}
{#            <label class="checkbox">#}
{#            <input type="checkbox" checked="checked" name="status"/>#}
{#            <span></span>Checked</label>#}
{#        </div>#}
{#    </div>#}

            <div class="card-footer">
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-10">
                        <input class="btn btn-primary" type="submit" value="Save" />
                      <input class="btn btn-primary" type="submit" name="add_text" value="Save and add another" />
                    </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}

adminka/templates/staff_edit.html
{% extends 'base.html' %}
{% load static%}
{% block content %}
    <!--end::Card-->
    <!--begin::Card-->
    <div class="card card-custom gutter-b example example-compact">
        <div class="card-header">
            <h3 class="card-title">add Staff</h3>

        </div>
        <!--begin::Form-->
       <form method="POST" action="" enctype="multipart/form-data">
                         {% csrf_token %}
            <div class="card-body">
                <div class="form-group mb-8">
                    <div class="alert alert-custom alert-default" role="alert">
                        <div class="alert-icon">
                            <span class="svg-icon svg-icon-primary svg-icon-xl">
                                <!--begin::Svg Icon | path:assets/media/svg/icons/Tools/Compass.svg-->
                                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                        <rect x="0" y="0" width="24" height="24" />
                                        <path d="M7.07744993,12.3040451 C7.72444571,13.0716094 8.54044565,13.6920474 9.46808594,14.1079953 L5,23 L4.5,18 L7.07744993,12.3040451 Z M14.5865511,14.2597864 C15.5319561,13.9019016 16.375416,13.3366121 17.0614026,12.6194459 L19.5,18 L19,23 L14.5865511,14.2597864 Z M12,3.55271368e-14 C12.8284271,3.53749572e-14 13.5,0.671572875 13.5,1.5 L13.5,4 L10.5,4 L10.5,1.5 C10.5,0.671572875 11.1715729,3.56793164e-14 12,3.55271368e-14 Z" fill="#000000" opacity="0.3" />
                                        <path d="M12,10 C13.1045695,10 14,9.1045695 14,8 C14,6.8954305 13.1045695,6 12,6 C10.8954305,6 10,6.8954305 10,8 C10,9.1045695 10.8954305,10 12,10 Z M12,13 C9.23857625,13 7,10.7614237 7,8 C7,5.23857625 9.23857625,3 12,3 C14.7614237,3 17,5.23857625 17,8 C17,10.7614237 14.7614237,13 12,13 Z" fill="#000000" fill-rule="nonzero" />
                                    </g>
                                </svg>
                                <!--end::Svg Icon-->
                            </span>
                        </div>

                </div>
                <div class="form-group">
                    <label>Ism</label>
                    <input  class="form-control" type="text" name="first_name" value={{ staff.first_name }}>
                </div>
   <div class="form-group">
                    <label>Familya</label>
                    <input  class="form-control" type="text" name="last_name" value={{ staff.last_name }}>
                </div>
   <div class="form-group">
                    <label>Otasini ismi</label>
                    <input  class="form-control" type="text" name="father_name" value={{ staff.father_name }}>
                </div>
	<div class="form-group">
        <label>Date</label>

            <input class="form-control" type="date"  name="birth_date" value="{{ staff.birth_date|date:'c' }}" />

    </div>
<div class="form-group">
        <label>File Browser</label>
{#        <div></div>#}
        <div class="custom-file">
            <input type="file" name="image" class="custom-file-input" />
            <label class="custom-file-label" >Choose file</label>
        </div>
    {% if staff.image %}
    <a href="{{ staff.image.url }}">{{ staff.image.name }}</a>
        {% endif %}

    </div>

<div class="form-group">
    <label>Status</label>
    <div></div>
    <select class="custom-select form-control" name="status">
        <option selected="selected" value={{ staff.status }}>{{ staff.get_status_display }}</option>
        {% if staff.status != "iiv" %}
        <option value="iiv">IIV</option>
        {% endif %}
      {% if staff.status != "not_iiv" %}
        <option value="not_iiv">Hali IIV  uchun ko'rib chiqilmagan</option>
     {% endif %}
  {% if staff.status != "delete_iiv" %}
        <option value="delete_iiv">IIVdan chiqarilgan</option>
     {% endif %}
    </select>
</div>
<div class="form-group">
            <label >Rank</label>
            <select class="form-control" name="rank">
              <option value={{staff.rank.id}} selected>{{ staff.rank.rank }}</option>
                {% for rank in ranks %}
                {% if rank.id != staff.rank.id %}
                  <option value={{rank.id}}>{{ rank.rank }}</option>
                    {%endif%}
                {% endfor %}
            </select>
        </div>

                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-2"></div>
                    <div class="col-10">
                        <input class="btn btn-primary" type="submit" value="Save" />


                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock content %}